### ISSUE TITLE
ycl_bw_tools_gui.clas.xml

### ISSUE THREAD

**Issue by larshp** [pawelwiejkut/bw_toolbox#2]
Hi,
Data is missing in file
https://github.com/pawelwiejkut/bw_toolbox/blob/master/src/ycl_bw_tools_gui.clas.xml
are you running the latest version of abapGit?

**Comment by pawelwiejkut** [comment]
Hello @larshp 
Last time I had some issues with my db space, and activation was probably not fully successful after my last pull. I will check what actually happen and give you know. Thanks for your attention !

**Comment by pawelwiejkut** [comment]
@larshp, all seems to be fine now. Thank you !
